apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: top-secret
        mountPath: /var/configuration/
  volumes:
    - name: top-secret
      secret:
        secretName: user-pass